import campk12 from "./assets/pngs/campk12.png";
import activeai from "./assets/pngs/activeai.png";
import mountblue from "./assets/pngs/mountblue.png";
import gupshup from "./assets/pngs/gupshup.png";
import wipro from "./assets/pngs/wipro.png";

export const ExperienceData = [
  {
    name: "WIPRO",
    client: "Optum - UHG",
    logo: wipro,
    duration: "May 2025 - Present",
    skills: [
      "JavaScript",
      "HTML",
      "CSS",
      "NextJS",
      "ReactJS",
      "Redux",
      "NodeJS",
      "Modele Federation",
      "Zustand",
    ],
    desc: [
      "Developing new features for an application called HR Command (HRC).",
      "Maintaining and enhancing existing features for two other applications: Broker Command and Command Profile.",
      "Writing unit tests and ensuring secure code standards in compliance with UHG guidelines.",
      "Leveraging AI technologies such as GitHub Copilot and ChatGPT for development, resulting in a 35% improvement in deliverables.",
      "Participating in refinement sessions to finalize UI requirements.",
      "Tracking and deploying production releases versions.",
      "Maintaining the codebase and managing DEV/QA/PROD deployments.",
      "Optimizing React components for better performance and efficiency.",
      "Developing clean, smooth, and responsive user interfaces.",
    ],
  },
  {
    name: "Gupshup",
    logo: gupshup,
    duration: "Jan 2023 - May 2025",
    skills: [
      "JavaScript",
      "NextJS",
      "ReactJS",
      "Modele Federation",
      "NodeJS",
      "Zustand",
      "Cucumber",
      "HTML",
      "CSS",
    ],
    desc: [
      "Implementing POC tasks and developing core features for Journey Builder.",
      "Writing unit tests and automation tests using the Cucumber framework.",
      "Leveraged AI technologies like Cursor, GitHub Copilot, and ChatGPT for development, resulting in a 15% improvement in deliverables.",
      "Implementing micro frontends architecture using Webpack Module Federation.",
      "Dockerized UI applications for consistent, scalable, and efficient deployments.",
      "Fixing security vulnerabilities to ensure compliance with all regulations.",
      "Implementing small to medium-sized backend tasks.",
      "Participating in grooming sessions to finalize UI requirements.",
      "Maintaining the codebase and tracking DEV/QA/PROD deployments.",
      "Optimizing React components for better performance and efficiency.",
      "Developing clean, smooth, and responsive user interfaces.",
    ],
  },
  {
    name: "CampK12",
    logo: campk12,
    duration: "July 2021 - Dec 2022",
    skills: [
      "NextJS",
      "ReactJS",
      "Redux",
      "NodeJS",
      "JavaScript",
      "HTML",
      "CSS",
    ],
    desc: [
      "Creating SEO optimized web pages.",
      "Developing clean, smooth, and responsive UI.",
      "Performing AB testing on the website.",
      "Tracking and improving page speed of web pages.",
      "Developing NextJS api routes.",
      "Leading/guiding 4 front-end developers, attending sprint planning, and assigning tasks.",
      "Taking care of Dev & Prod deployments.",
    ],
  },
  {
    name: "Active.Ai",
    logo: activeai,
    duration: "Feb 2019 - July 2021",
    skills: [
      "ReactJS",
      "Redux",
      "NodeJS",
      "jQuery",
      "JavaScript",
      "HTML",
      "CSS",
    ],
    desc: [
      "Creating new chatbots UI from scratch, and developing new features & functionalities in chatbots.",
      "Creating and developing new React components for the admin dashboard and fixing bugs.",
      "Integrating and deploying chatbots on clients websites.",
      "Developing internal Feedback site.",
    ],
  },
  {
    name: "MountBlue Tech",
    logo: mountblue,
    duration: "Dec 2018 - Feb 2019",
    skills: ["ReactJS", "NodeJS", "JavaScript", "jQuery", "HTML", "CSS"],
    desc: [
      "Training on Front-End technologies.",
      "Developing web apps using NodeJS, Express, ReactJS, MongoDB.",
    ],
  },
];
